pipeline {
    agent any
    environment {
        GH_TOKEN = "bda63c08c449d56746b1c9ca702f29fb592dbc01"
        PATH = "/opt/sonar-scanner/bin:$PATH"
    }
    stages {
        stage("clone code") {
            steps {
                git credentialsId: 'githublogin', branch: 'master', url: 'https://github.com/Ajayalla/simple-node-js-react-npm-app.git'
            }
        }
        stage("build code") {
            steps {
                sh "npm install"
                sh "npm run electron:build"
            }
        }
        stage('SonarQube Analysis') {
            steps {
              //withSonarQubeEnv('sonarqube') {
                sh "sonar-scanner"
              //}
            }
        }
    }
}
