pipeline {
    agent any
    environment {
        GH_TOKEN = "29d221ef372c887db854ee66cde77bff199a9df9"
        PATH = "/opt/sonar-scanner/bin:$PATH"
    }
    stages {
        stage("clone code") {
            steps {
                git credentialsId: 'git_credentials', branch: 'develop', url: 'https://github.com/Ajayalla/simple-node-js-react-npm-app.git'
            }
        }
        stage("build code") {
            steps {
                sh "npm install"
                sh "npm run electron:build"
            }
        }
        stage('SonarQube Analysis') {
            steps {
              //withSonarQubeEnv('sonarqube') {
                sh "sonar-scanner"
              //}
            }
        }
    }
}
